title: Suttna's Blog

url: https://blog.suttna.com

website_url: https://suttna.com

twitter_username: suttnabot
github_username: suttna
instagram_username: suttnabot
facebook_username: Suttna-870854276395480

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-assets

sass:
  load_paths:
    - _sass
    - node_modules

exclude:
  - vendor
  - node_modules

assets:
  prefix: "/assets"
  assets:
    - "*.png"
    - "bundle.css"
  sources:
    - node_modules/
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js
  features:
    liquid: true
    integrity: true
    automatic_img_size: false
    automatic_img_alt: false
